version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80"
    depends_on:
      - php
    networks:
      - internal

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    environment:
      - DB_HOST=mysql-motaparfum-ho8oko
      - DB_NAME=motaparfum
      - DB_USER=motaparfum
      - DB_PASS=Gucci1826
    networks:
      - internal

networks:
  internal:
