server {
    listen 80;
    server_name _;
    
    root /var/www/html/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        alias /var/www/html/backend/api/;
        try_files $uri $uri/ =404;

        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            # $request_filename is mapped from alias
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }
}
